In [1]:
import numpy as np
import mne
%matplotlib inline
import matplotlib.pyplot as plt
import scipy 
from scipy.stats import hmean,trim_mean
import pandas as pd

In [2]:
raw = mne.io.read_raw_fif("suj28_l2nap_day1.fif", preload = True)
print(raw.info)
print(raw.ch_names)

Opening raw data file C:\Users\Sammauel\Documents\csc59969\EEG\EEG-Visualization\Inspection\suj28_l2nap_day1.fif...
This filename (C:\Users\Sammauel\Documents\csc59969\EEG\EEG-Visualization\Inspection\suj28_l2nap_day1.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
Isotrak not found
    Read a total of 1 projection items:
        Average EEG reference (1 x 61)  idle
    Range : 0 ... 1807649 =      0.000 ...  1807.649 secs
Ready.
add_eeg_ref defaults to True in 0.13, will default to False in 0.14, and will be removed in 0.15. We recommend to use add_eeg_ref=False and set_eeg_reference() instead.
Reading 0 ... 1807649  =      0.000 ...  1807.649 secs...

<ipython-input-2-9c1e9f787b83>:1: RuntimeWarning: This filename (C:\Users\Sammauel\Documents\csc59969\EEG\EEG-Visualization\Inspection\suj28_l2nap_day1.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  raw = mne.io.read_raw_fif("suj28_l2nap_day1.fif", preload = True)
<ipython-input-2-9c1e9f787b83>:1: DeprecationWarning: add_eeg_ref defaults to True in 0.13, will default to False in 0.14, and will be removed in 0.15. We recommend to use add_eeg_ref=False and set_eeg_reference() instead.
  raw = mne.io.read_raw_fif("suj28_l2nap_day1.fif", preload = True)

<Info | 19 non-empty fields
    bads : 'list | 0 items
    buffer_size_sec : 'numpy.float64 | 1.0
    ch_names : 'list | Fp1, Fz, F3, F7, FT9, FC5, FC1, C3, T7, CP5
    chs : 'list | 63 items (EEG: 61, EOG: 2)
    comps : 'list | 0 items
    custom_ref_applied : 'bool | False
    dev_head_t : 'mne.transforms.Transform | 3 items
    events : 'list | 0 items
    file_id : 'dict | 4 items
    filename : 'str | C:\Users\S.../suj28_l2nap_day1.fif
    highpass : 'float | 0.10000000149011612 Hz
    hpi_meas : 'list | 0 items
    hpi_results : 'list | 0 items
    lowpass : 'float | 50.0 Hz
    meas_date : 'numpy.ndarray | 2016-10-02 14:00:07
    meas_id : 'dict | 4 items
    nchan : 'int | 63
    projs : 'list | Average EEG reference: off
    sfreq : 'float | 1000.0 Hz
    acq_pars : 'NoneType
    acq_stim : 'NoneType
    ctf_head_t : 'NoneType
    description : 'NoneType
    dev_ctf_t : 'NoneType
    dig : 'NoneType
    experimenter : 'NoneType
    hpi_subsystem : 'NoneType
    kit_system_id : 'NoneType
    line_freq : 'NoneType
    proj_id : 'NoneType
    proj_name : 'NoneType
    subject_info : 'NoneType
    xplotter_layout : 'NoneType
>
['Fp1', 'Fz', 'F3', 'F7', 'FT9', 'FC5', 'FC1', 'C3', 'T7', 'CP5', 'CP1', 'Pz', 'P3', 'P7', 'O1', 'Oz', 'O2', 'P4', 'P8', 'TP10', 'CP6', 'CP2', 'Cz', 'C4', 'T8', 'FT10', 'FC6', 'FC2', 'F4', 'F8', 'Fp2', 'AF7', 'AF3', 'AFz', 'F1', 'F5', 'FT7', 'FC3', 'FCz', 'C1', 'C5', 'TP7', 'CP3', 'P1', 'P5', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'P6', 'P2', 'CPz', 'CP4', 'TP8', 'C6', 'C2', 'FC4', 'FT8', 'F6', 'F2', 'LOc', 'ROc']

In [3]:
raw.load_data()
raw.resample(10)

In [6]:
df = raw.to_data_frame(picks=None, index=None, scale_time=1000.0, scalings=dict(eeg=1), copy=True, start=None, stop=None)
df.head()

Converting time column to int64...

signal,Fp1,Fz,F3,F7,FT9,FC5,FC1,C3,T7,CP5,...,CP4,TP8,C6,C2,FC4,FT8,F6,F2,LOc,ROc
time,,,,,,,,,,,,,,,,,,,,,
0,11607.189936,14893.280850,15708.377604,1512.585225,6591.296067,-898.787251,18075.431582,16503.607833,13248.552848,14890.099683,...,16981.732797,3983.475638,21690.807722,6378.633979,17877.619873,1655.989342,-1911.685458,16699.364974,2.392143e+10,7.073098e+09
100,11555.578653,15299.300894,15693.479940,1436.988655,6829.300896,-1011.861941,18168.177774,16772.396012,13415.294053,14701.752851,...,17048.662575,3809.184469,21818.078421,6353.064430,18072.641849,1576.326706,-1874.566798,16210.705241,2.386367e+10,7.010113e+09
200,11540.766520,15416.880237,15683.965824,1412.987570,6884.302009,-1041.261801,18190.168586,16843.484548,13460.361477,14651.672472,...,17063.569609,3765.031605,21847.284388,6344.277508,18118.784003,1554.908005,-1870.197107,16095.181204,2.380634e+10,6.937458e+09
300,11512.506610,15604.173968,15673.798529,1376.670943,7001.180145,-1100.937336,18231.458615,16965.471244,13537.960218,14555.517641,...,17094.423257,3671.677613,21905.517271,6329.353178,18212.366861,1512.629428,-1858.585829,15858.023247,2.377906e+10,6.882754e+09
400,11517.604170,15520.944267,15677.104511,1387.739775,6962.857434,-1087.945724,18217.714150,16920.458397,13501.012309,14584.542714,...,17081.147297,3694.949214,21884.120521,6331.899204,18181.946706,1522.776348,-1860.484833,15916.993788,2.380877e+10,6.898872e+09

# Ignore channels: LOc and ROc.  They offer nothing to the data.

In [8]:
df.drop(df.columns[[61, 62]], axis=1, inplace=True)
df.head()

signal,Fp1,Fz,F3,F7,FT9,FC5,FC1,C3,T7,CP5,...,P2,CPz,CP4,TP8,C6,C2,FC4,FT8,F6,F2
time,,,,,,,,,,,,,,,,,,,,,
0,11607.189936,14893.280850,15708.377604,1512.585225,6591.296067,-898.787251,18075.431582,16503.607833,13248.552848,14890.099683,...,19619.810818,20210.998224,16981.732797,3983.475638,21690.807722,6378.633979,17877.619873,1655.989342,-1911.685458,16699.364974
100,11555.578653,15299.300894,15693.479940,1436.988655,6829.300896,-1011.861941,18168.177774,16772.396012,13415.294053,14701.752851,...,19748.022261,20310.568130,17048.662575,3809.184469,21818.078421,6353.064430,18072.641849,1576.326706,-1874.566798,16210.705241
200,11540.766520,15416.880237,15683.965824,1412.987570,6884.302009,-1041.261801,18190.168586,16843.484548,13460.361477,14651.672472,...,19777.992983,20333.166334,17063.569609,3765.031605,21847.284388,6344.277508,18118.784003,1554.908005,-1870.197107,16095.181204
300,11512.506610,15604.173968,15673.798529,1376.670943,7001.180145,-1100.937336,18231.458615,16965.471244,13537.960218,14555.517641,...,19839.064039,20381.218309,17094.423257,3671.677613,21905.517271,6329.353178,18212.366861,1512.629428,-1858.585829,15858.023247
400,11517.604170,15520.944267,15677.104511,1387.739775,6962.857434,-1087.945724,18217.714150,16920.458397,13501.012309,14584.542714,...,19815.927383,20364.087903,17081.147297,3694.949214,21884.120521,6331.899204,18181.946706,1522.776348,-1860.484833,15916.993788

In [10]:
## To save this as csv run the following
#df.to_csv("suj28_l2nap_day1_100ms.csv")

df1 = pd.read_csv("suj28_l2nap_day1_100ms.csv")
df1.head()

# The reason behind this is that the orignal conversion was set at 1.7 GB which is a really huge file size.
#I wanted to reduce said size for D3 parsing because it would take forever to load which might be an issue.
# This should be a temporary soln until I mess around with converting it to JSON

,time,Fp1,Fz,F3,F7,FT9,FC5,FC1,C3,T7,...,P2,CPz,CP4,TP8,C6,C2,FC4,FT8,F6,F2
0,0,11607.189936,14893.280850,15708.377604,1512.585225,6591.296067,-898.787251,18075.431582,16503.607833,13248.552848,...,19619.810818,20210.998224,16981.732797,3983.475638,21690.807722,6378.633979,17877.619873,1655.989342,-1911.685458,16699.364974
1,100,11555.578653,15299.300894,15693.479940,1436.988655,6829.300896,-1011.861941,18168.177774,16772.396012,13415.294053,...,19748.022261,20310.568130,17048.662575,3809.184469,21818.078421,6353.064430,18072.641849,1576.326706,-1874.566798,16210.705241
2,200,11540.766520,15416.880237,15683.965824,1412.987570,6884.302009,-1041.261801,18190.168586,16843.484548,13460.361477,...,19777.992983,20333.166334,17063.569609,3765.031605,21847.284388,6344.277508,18118.784003,1554.908005,-1870.197107,16095.181204
3,300,11512.506610,15604.173968,15673.798529,1376.670943,7001.180145,-1100.937336,18231.458615,16965.471244,13537.960218,...,19839.064039,20381.218309,17094.423257,3671.677613,21905.517271,6329.353178,18212.366861,1512.629428,-1858.585829,15858.023247
4,400,11517.604170,15520.944267,15677.104511,1387.739775,6962.857434,-1087.945724,18217.714150,16920.458397,13501.012309,...,19815.927383,20364.087903,17081.147297,3694.949214,21884.120521,6331.899204,18181.946706,1522.776348,-1860.484833,15916.993788

## Next step is to convert JSON